#!/bin/bash
APT_DIR=~/android-sdk-macosx/platform-tools
$APT_DIR/adb uninstall com.professionalperformance.geotracker
$APT_DIR/adb install GeoTracker.apk
$APT_DIR/adb shell am start -n com.professionalperformance.geotracker/.EnforceGPSActivity
$APT_DIR/adb shell am broadcast -a android.intent.action.BOOT_COMPLETED
